### ISSUE TITLE
ep3 72 00:05:00,010 --> 00:05:08,100 Therefore, as we rotate the upper body to the end of the turn like this when we do a heel side edge sliding may occur

### ISSUE THREAD

**Issue by lgawron** [lgawron/open-snowboard-project#2]
do you mean:

if we rotate the upper body part (without pelvis) - an edge slip can occur
that is why we have to rotate minding the pelvis ?

**Comment by lgawron** [comment]
From the exact translation I rather get: if you rotate the torso during turn an edge sliding might occur. Which is probably not what you wanted to say.

**Comment by lgawron** [comment]
oh. we talked about it - you meant do not OVERROTATE, just actively keep the rotation in mind.

**Comment by seungwon-kim** [comment]
I think already have talking about this. you understood this. right?

**Comment by seungwon-kim** [comment]
this issue resolved?? if yes, please close
